Task8
htmlacademy-adaptive/1856745-cat-energy-24 pull request #12
Opened 2022-01-20 23:17 UTC by andreyka9678

2022-01-20 23:21 UTC, andreyka9678 commented
Не работает import csso from 'postcss-csso'; в gulpfile.js, пришлось его закомментировать, выдает сообщение, а остальное ОК
PS C:\Users\Home\1856745-cat-energy-24> npm start

> cat-energy-24@ start C:\Users\Home\1856745-cat-energy-24
> gulp

file:///C:/Users/Home/1856745-cat-energy-24/node_modules/css-tree/lib/generator/sourceMap.js:1
import { SourceMapGenerator } from 'source-map-js/lib/source-map-generator.js';
         ^^^^^^^^^^^^^^^^^^
SyntaxError: The requested module 'source-map-js/lib/source-map-generator.js' does not provide an export named 'SourceMapGenerator'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:92:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:107:20)
    at async Loader.import (internal/modules/esm/loader.js:179:24)
    at async importModuleDynamicallyWrapper (internal/vm/module.js:422:15)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cat-energy-24@ start: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cat-energy-24@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Home\AppData\Roaming\npm-cache\_logs\2022-01-20T23_12_08_291Z-debug.log
PS C:\Users\Home\1856745-cat-energy-24>

2022-01-21 09:54 UTC, andreysgra requested changes
Почему здесь не исправлено?
![image](https://user-images.githubusercontent.com/17790771/150500221-46abc506-d450-4991-8ac6-89011019b1bd.png)
Как у вас будет работать `npm run build`?

---

Что касается вопроса про ошибку с `csso`: когда я установил новые зависимости, которые вы добавили в этом задании, то у меня сборка вообще перестала запускаться. Команда `npm start` сообщала, что `gulp` является неизвестной командой. Поскольку в `gulpfile.js`, `package.json` всё выглядело правильно, а пакет `gulp` был установлен и находился в папке `node_modules`, то я решил, что в вашей сборке что-то пошло не так. Удалил папку `node_modules` и файл `package-lock.json`, а затем заново установил зависимости - `npm i`. Запустил сборку командой`npm start`  - всё прошло успешно. Затем убрал в `gulpfile.js` комментарии со строк про `csso`, снова запустил сборку. Ошибок, как описали вы, не появилось. Проект успешно собрался, а файл `style.min.css` действительно минифицировался, о чём можно понять по такому содержимому файла:
![image](https://user-images.githubusercontent.com/17790771/150503229-ebeaead4-2594-4e75-bfa8-5d6da7aaaf19.png)

Советую вам поступить точно также.

2022-01-21 09:54 UTC, andreysgra commented on gulpfile.js
>  }
В этом задании происходит просто копирование файла скрипта, а не минификация. Для минификации нужно использовать модуль `terser`.

2022-01-21 09:54 UTC, andreysgra commented on gulpfile.js
> +}
В этом задании вы собираете файл векторного спрайта, но при этом спрайт встроен в HTML и путь в `use` обращается к нему. Нужно убрать из разметки встроенный спрайт и переписать пути в `use`  на работу с внешним файлом.

2022-01-21 09:54 UTC, andreysgra commented on gulpfile.js
> +  return gulp.src('source/img/icons/*.svg')
Здесь вы обращаетесь к файлам по несуществующему пути (папки `icons` у вас нет), соответственно файл спрайта не будет собран.

2022-01-23 08:45 UTC, merged